### ISSUE TITLE
Can not use Furnaces, Droppers or Dispensers

### ISSUE THREAD

**Issue by VikeStep** [AlgorithmX2/RotatableBlocks#11]
With RotatableBlocks I can not use furnaces, droppers or dispensers

Other information:
Forge: 10.12.1.1085
MC: 1.7.2
RB: Build 5

Reproduce:
1. Go into a world
2. Craft/Spawn in furnace, dropper or dispenser (happens in both SMP and SSP)
3. Place it and try to use it
4. Does not open

Console Log: http://pastebin.com/TsCsJ6Tx

There are also no other mods installed.

**Comment by AlgorithmX2** [comment]
Fixed.
