### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by idealjo** [AlgorithmX2/RotatableBlocks#13]
crash with ender io conduit

gonna report to crazypants too

log:
http://pastebin.com/1ZcTvxAn

**Comment by AlgorithmX2** [comment]
I'm not sure there is anything I can do about that crash, looks like a weird de-sync between the block and the tile entity, in this case somehow a RBlocks tiles get into the block of an EnderIO Block.

Is there anyway to reproduce this by placing thing, or something?

**Comment by idealjo** [comment]
I will make some test but I had to remove rotatable block mod to login again into the world. waiting from ender io report too.

**Comment by CrazyPants** [comment]
As AlgorithmX2 said, this really shouldn't be possible. If you can reproduce it I will try and figure out what is happening.

**Comment by idealjo** [comment]
cannot reproduce the bug. wierd. no clue to what happened. sorry, this is a time waste now. close the issue if you want

**Comment by AlgorithmX2** [comment]
Fixed in new Rotatable Blocks Bulid 8
