### ISSUE TITLE
1.7.2 Build 6 - ExtraUtilities Crash

### ISSUE THREAD

**Issue by AgeOfPwn** [AlgorithmX2/RotatableBlocks#14]
![screenshot_25](https://cloud.githubusercontent.com/assets/8274973/3711068/3f8d5e68-14bd-11e4-9c98-eaa9aa801708.jpg)

I have tested the error without this mod installed, and it does not crash. http://pastebin.com/v2QjMS7h

How to reproduce...
1: Load unstable ftb 1.7.2 modpack
2: Set up extra utilities generator,energy extraction pipe and energy pipe exactly like the screenshot.
3: place lever on side of block marked by red square.
4: world will crash and become unplayable.
(World can be salvaged by uninstalling/disabling rotatableblocks)

EnderIO conduits do not seem to cause the same issue, I did not test with other pipes.

**Comment by AlgorithmX2** [comment]
Build 6 is old update

**Comment by AlgorithmX2** [comment]
Closing - No Reponse.
