### ISSUE TITLE
Crash with mods using this.canSilkHarvest();

### ISSUE THREAD

**Issue by msrEagle** [AlgorithmX2/RotatableBlocks#17]
I was reported a crash by a user of my mod, see https://github.com/GustoniaEagle/Adventurers-Amulets/issues/9

I was able to fix this issue by removing this.canSilkHarvest() from the conflicting block, but it seems illogical that the issue is on my end.

See https://github.com/GustoniaEagle/Adventurers-Amulets/commit/6d2caf62c47dbbe06cfe917cb52d0fda67013cb4 for the fix on my end, not sure what the issue is on RB's side.

**Comment by AlgorithmX2** [comment]
While I did fix the issue, i'm not sure why you were calling this method in your init method anyway, its a getter for if you can slik touch the block.
