### ISSUE TITLE
RotateableBlocks Core ( Cannot find Tool In-Game )

### ISSUE THREAD

**Issue by xXYoyonessXx** [AlgorithmX2/RotatableBlocks#19]
When I go to the mod list it says "No mod information found" for the RotateableBlocks Core. This is preventing me from using the mod as you would guess. I'm not quite sure what's wrong with the file but I have tried reinstalling it and had no luck.
![2015-01-21_16 26 27](https://cloud.githubusercontent.com/assets/10640529/5845535/b6749974-a18a-11e4-8e73-4f2940d187a7.png)

**Comment by AlgorithmX2** [comment]
Why would not having information on the Mod List for the Core prevent you from using it? I don't see the issue.

**Comment by xXYoyonessXx** [comment]
I don't know. The rotatable blocks mod just doesn't exist ingame unless the tool is in a specific category like tools, combat, etc.

**Comment by AlgorithmX2** [comment]
The wrench must be enabled with

settings {
    B:enableWrench=true
}

and its under tools, it has no creative tab of its own since its just a single item.

Also tested, and its working fine.

**Comment by xXYoyonessXx** [comment]
Thank you.

**Comment by xXYoyonessXx** [comment]
Wait, where do I go to do that?

**Comment by AlgorithmX2** [comment]
in the config/ folder theres a RotatableBlocks config file, its in there.
