### ISSUE TITLE
carpenters and rotatable blocks don't play nice

### ISSUE THREAD

**Issue by zpowerup** [AlgorithmX2/RotatableBlocks#4]
http://imgur.com/miChHKG
as soon as i remove rotatable blocks i can place any block on carpenters block

**Comment by AlgorithmX2** [comment]
I assume this is because Carpenter blocks won't let you use blocks with tile entities in it... there probably needs to be some sort of integration to fix this.

**Comment by AlgorithmX2** [comment]
Fixed!
