### ISSUE TITLE
Bug or intentional?

### ISSUE THREAD

**Issue by ProfoundGames** [AlgorithmX2/RotatableBlocks#5]
Well if you rotate a grass block it turns into a dirt block. and i don't know if this is intentional or on purpose but if you don't tell the mod dev, they don't know about it!

If you want me to I made a quick video about it :)

**Comment by AlgorithmX2** [comment]
Yeah its intentional MC's grass stuff doesn't play well with R-Blocks. it basically leaves the grass on top and rotates the sides XD which looks really silly so I just turned it into to dirt when you do that.
